# train:
train-distortion-type:  gauss_0.3
train-distortion-parts: rand_0.8
train-distortion-temporal:  0.3
train-gen-conf-score: None

# test:
test-distortion-type:  gauss_0.3
test-distortion-parts: rand_0.8
test-distortion-temporal:  0.3
test-gen-conf-score: None

loss-ignore_parts: None
eval-ignore_parts: None