# train:
train-distortion-type:  gauss_0.1
train-distortion-parts: rand_0.3
train-distortion-temporal:  0.3
train-gen-conf-score: gauss

# test:
test-distortion-type:  gauss_0.1
test-distortion-parts: rand_0.3
test-distortion-temporal:  0.3
test-gen-conf-score: binary

loss-ignore_parts: None
eval-ignore_parts: None