# train:
train-distortion-type:  gauss_0.05
train-distortion-parts: rand_0.2
train-distortion-temporal:  0.2
train-gen-conf-score: None

# test:
test-distortion-type:  gauss_0.05
test-distortion-parts: rand_0.2
test-distortion-temporal: 0.2
test-gen-conf-score: None

loss-ignore_parts: None
eval-ignore_parts: None