# train:
train-distortion-type:  impulse_0.2
train-distortion-parts: rand_0.3
train-distortion-temporal:  0.2
train-gen-conf-score: None

# test:
test-distortion-type:  impulse_0.2
test-distortion-parts: rand_0.3
test-distortion-temporal:  0.2
test-gen-conf-score: None

loss-ignore_parts: None
eval-ignore_parts: None