# train:
train-distortion-type:  impulse_0.8
train-distortion-parts: rand_0.5
train-distortion-temporal:  0.5
train-gen-conf-score: impulse

# test:
test-distortion-type:  impulse_0.8
test-distortion-parts: rand_0.5
test-distortion-temporal:  0.5
test-gen-conf-score: impulse

loss-ignore_parts: None
eval-ignore_parts: None